//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniTech.MiniCoder.Core.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Arabic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Arabic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniTech.MiniCoder.Core.Languages.Arabic", typeof(Arabic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأدوات.
        /// </summary>
        internal static string applicationsButton {
            get {
                return ResourceManager.GetString("applicationsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :معدل البت.
        /// </summary>
        internal static string audioBitrate {
            get {
                return ResourceManager.GetString("audioBitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :المرمز.
        /// </summary>
        internal static string audioCodec {
            get {
                return ResourceManager.GetString("audioCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحليل الصوت.
        /// </summary>
        internal static string audioDecodingMessage {
            get {
                return ResourceManager.GetString("audioDecodingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحويل الصوت إلى.
        /// </summary>
        internal static string audioEncodingMessage {
            get {
                return ResourceManager.GetString("audioEncodingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحويل المسار الصوتي.
        /// </summary>
        internal static string audioEncodingTrack {
            get {
                return ResourceManager.GetString("audioEncodingTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خيارات الصوت.
        /// </summary>
        internal static string audioOptionsTitle {
            get {
                return ResourceManager.GetString("audioOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصوت.
        /// </summary>
        internal static string audioTabTitle {
            get {
                return ResourceManager.GetString("audioTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :الصيغة.
        /// </summary>
        internal static string containerFormat {
            get {
                return ResourceManager.GetString("containerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحاوي.
        /// </summary>
        internal static string containerOptionsTitle {
            get {
                return ResourceManager.GetString("containerOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النواة.
        /// </summary>
        internal static string coreTabTitle {
            get {
                return ResourceManager.GetString("coreTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخصيص.
        /// </summary>
        internal static string customButton {
            get {
                return ResourceManager.GetString("customButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        internal static string customFilterCancel {
            get {
                return ResourceManager.GetString("customFilterCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إذا أردت تعطيل المرشح الافتراضي، فعطله في تبويب الضبط.
        /// </summary>
        internal static string customFilterNote {
            get {
                return ResourceManager.GetString("customFilterNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافق.
        /// </summary>
        internal static string customFilterOK {
            get {
                return ResourceManager.GetString("customFilterOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المخصصة AviSynth أدخل إعدادات.
        /// </summary>
        internal static string customFilterText {
            get {
                return ResourceManager.GetString("customFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخصيص المرشحات.
        /// </summary>
        internal static string customFilterTitle {
            get {
                return ResourceManager.GetString("customFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان الملفات.
        /// </summary>
        internal static string customPathsTitle {
            get {
                return ResourceManager.GetString("customPathsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فك التجميع.
        /// </summary>
        internal static string demuxingAbortedMessage {
            get {
                return ResourceManager.GetString("demuxingAbortedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتهى التجميع.
        /// </summary>
        internal static string demuxingCompleteMessage {
            get {
                return ResourceManager.GetString("demuxingCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التجميع.
        /// </summary>
        internal static string demuxingMessage {
            get {
                return ResourceManager.GetString("demuxingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MKV فك تجميع الملفات من.
        /// </summary>
        internal static string demuxingMkv {
            get {
                return ResourceManager.GetString("demuxingMkv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فك تجميع المرفقات.
        /// </summary>
        internal static string demuxingMkvAttachments {
            get {
                return ResourceManager.GetString("demuxingMkvAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فك تجميع التشابترز.
        /// </summary>
        internal static string demuxingMkvChapters {
            get {
                return ResourceManager.GetString("demuxingMkvChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP4 استخراج المسار الصوتي من.
        /// </summary>
        internal static string demuxingmp4Audio {
            get {
                return ResourceManager.GetString("demuxingmp4Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP4 استخراج الفيديو من.
        /// </summary>
        internal static string demuxingmp4Video {
            get {
                return ResourceManager.GetString("demuxingmp4Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOB تتم فهرسة ملفات.
        /// </summary>
        internal static string demuxingVob {
            get {
                return ResourceManager.GetString("demuxingVob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يتم استخراج التشابترز.
        /// </summary>
        internal static string demuxingvobChapters {
            get {
                return ResourceManager.GetString("demuxingvobChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يتم استخراج الترجمة.
        /// </summary>
        internal static string demuxingvobSubs {
            get {
                return ResourceManager.GetString("demuxingvobSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابدأ.
        /// </summary>
        internal static string encodeStartButton {
            get {
                return ResourceManager.GetString("encodeStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توقف.
        /// </summary>
        internal static string encodeStopButton {
            get {
                return ResourceManager.GetString("encodeStopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتهى الإنتاج.
        /// </summary>
        internal static string encodingComplete {
            get {
                return ResourceManager.GetString("encodingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجاهل المرفقات.
        /// </summary>
        internal static string encodingIgnoreAttachments {
            get {
                return ResourceManager.GetString("encodingIgnoreAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجاهل الصوت.
        /// </summary>
        internal static string encodingIgnoreAudio {
            get {
                return ResourceManager.GetString("encodingIgnoreAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجاهل التشابترز.
        /// </summary>
        internal static string encodingIgnoreChapters {
            get {
                return ResourceManager.GetString("encodingIgnoreChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجاهل الترجمة.
        /// </summary>
        internal static string encodingIgnoreSubs {
            get {
                return ResourceManager.GetString("encodingIgnoreSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابدأ بالعملية التالية في حال وجود خطأ في السابقة.
        /// </summary>
        internal static string encodingNextError {
            get {
                return ResourceManager.GetString("encodingNextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (اعرض الفيديو (لتصحيح الأخطاء فقط.
        /// </summary>
        internal static string encodingShowVideoPreview {
            get {
                return ResourceManager.GetString("encodingShowVideoPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإنتاج.
        /// </summary>
        internal static string encodingTitle {
            get {
                return ResourceManager.GetString("encodingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنتاج الفيديو.
        /// </summary>
        internal static string encodingVideoPass {
            get {
                return ResourceManager.GetString("encodingVideoPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theora إنتاج فيديو نوع.
        /// </summary>
        internal static string encodingVideoTheora {
            get {
                return ResourceManager.GetString("encodingVideoTheora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يبدو أن خطأً قد حدث، أتود أن ترسل تقريرًا؟.
        /// </summary>
        internal static string errorWarningMessage {
            get {
                return ResourceManager.GetString("errorWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !خطأ.
        /// </summary>
        internal static string errorWarningTitle {
            get {
                return ResourceManager.GetString("errorWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحليل معلومات الملف.
        /// </summary>
        internal static string fileInfoFetch {
            get {
                return ResourceManager.GetString("fileInfoFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خيارات المرشحات.
        /// </summary>
        internal static string filterOptionsTitle {
            get {
                return ResourceManager.GetString("filterOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVC فهرسة.
        /// </summary>
        internal static string indexingAvc {
            get {
                return ResourceManager.GetString("indexingAvc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أُلغيت الفهرسة.
        /// </summary>
        internal static string indexingAvcAbort {
            get {
                return ResourceManager.GetString("indexingAvcAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVC انتهت فهرسة.
        /// </summary>
        internal static string indexingAvcCompleted {
            get {
                return ResourceManager.GetString("indexingAvcCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضع الاستعداد.
        /// </summary>
        internal static string infoLabel {
            get {
                return ResourceManager.GetString("infoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (المدخلات (حدد الملفات متغيرة الفريمات.
        /// </summary>
        internal static string inputColumn1Title {
            get {
                return ResourceManager.GetString("inputColumn1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أُلغيت الفهرسة.
        /// </summary>
        internal static string inputColumn2StatusAborted {
            get {
                return ResourceManager.GetString("inputColumn2StatusAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتهى.
        /// </summary>
        internal static string inputColumn2StatusDone {
            get {
                return ResourceManager.GetString("inputColumn2StatusDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإنتاج.
        /// </summary>
        internal static string inputColumn2StatusEncoding {
            get {
                return ResourceManager.GetString("inputColumn2StatusEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ.
        /// </summary>
        internal static string inputColumn2StatusError {
            get {
                return ResourceManager.GetString("inputColumn2StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضع الاستعداد.
        /// </summary>
        internal static string inputColumn2StatusReady {
            get {
                return ResourceManager.GetString("inputColumn2StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        internal static string inputColumn2StatusTitle {
            get {
                return ResourceManager.GetString("inputColumn2StatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدخلات.
        /// </summary>
        internal static string inputTabTitle {
            get {
                return ResourceManager.GetString("inputTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخ.
        /// </summary>
        internal static string logMenuCopy {
            get {
                return ResourceManager.GetString("logMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أرسل تقرير خلل في البرنامج.
        /// </summary>
        internal static string logMenuSend {
            get {
                return ResourceManager.GetString("logMenuSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السجل.
        /// </summary>
        internal static string logTabTitle {
            get {
                return ResourceManager.GetString("logTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        internal static string menuAdd {
            get {
                return ResourceManager.GetString("menuAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف الكل.
        /// </summary>
        internal static string menuClear {
            get {
                return ResourceManager.GetString("menuClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        internal static string menuRemove {
            get {
                return ResourceManager.GetString("menuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجميع إلى.
        /// </summary>
        internal static string muxingMessage {
            get {
                return ResourceManager.GetString("muxingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجميع\فك التجميع.
        /// </summary>
        internal static string muxingTabTitle {
            get {
                return ResourceManager.GetString("muxingTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخبارنا.
        /// </summary>
        internal static string newsTabTitle {
            get {
                return ResourceManager.GetString("newsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خيارات.
        /// </summary>
        internal static string optionsTabTitle {
            get {
                return ResourceManager.GetString("optionsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخرى.
        /// </summary>
        internal static string otherTabTitle {
            get {
                return ResourceManager.GetString("otherTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :مكان الإخراج.
        /// </summary>
        internal static string outputDirectory {
            get {
                return ResourceManager.GetString("outputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعطيل خاصية تعديل أسماء الملفات المنتجة.
        /// </summary>
        internal static string outputDisableVideoAdvert {
            get {
                return ResourceManager.GetString("outputDisableVideoAdvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضبط الإخراج.
        /// </summary>
        internal static string outputSettingsTitle {
            get {
                return ResourceManager.GetString("outputSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأدوات المساعدة.
        /// </summary>
        internal static string pluginsTabTitle {
            get {
                return ResourceManager.GetString("pluginsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخفيف التشويش.
        /// </summary>
        internal static string postDenoiser {
            get {
                return ResourceManager.GetString("postDenoiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء;بسيطة;متوسطة;قوية;شديدة.
        /// </summary>
        internal static string postDenoiserOptions {
            get {
                return ResourceManager.GetString("postDenoiserOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعد العلمية.
        /// </summary>
        internal static string postprocessingOptionsTitle {
            get {
                return ResourceManager.GetString("postprocessingOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :الشحذ.
        /// </summary>
        internal static string postSharpen {
            get {
                return ResourceManager.GetString("postSharpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء;بسيطة;متوسطة;قوية;شديدة.
        /// </summary>
        internal static string postSharpenOptions {
            get {
                return ResourceManager.GetString("postSharpenOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :الترجمة.
        /// </summary>
        internal static string postSubtitle {
            get {
                return ResourceManager.GetString("postSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :الحقل.
        /// </summary>
        internal static string preField {
            get {
                return ResourceManager.GetString("preField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبل العملية.
        /// </summary>
        internal static string preprocessingOptionsTitle {
            get {
                return ResourceManager.GetString("preprocessingOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :الأبعاد.
        /// </summary>
        internal static string preResize {
            get {
                return ResourceManager.GetString("preResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء;ناعم;معتدل;مشحوذ;(Lanczos64) مشحوذ جدًا;(spline36) مشحوذ جدًا.
        /// </summary>
        internal static string preResizeOptions {
            get {
                return ResourceManager.GetString("preResizeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :الارتفاع/العرض.
        /// </summary>
        internal static string preWidthHeight {
            get {
                return ResourceManager.GetString("preWidthHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :الأولوية.
        /// </summary>
        internal static string processPriority {
            get {
                return ResourceManager.GetString("processPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منخفضة;تحت الافتراضية;افتراضية;فوق الافتراضية;عالية;الزمن الفعلي.
        /// </summary>
        internal static string processPriorityOptions {
            get {
                return ResourceManager.GetString("processPriorityOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضبط العملية.
        /// </summary>
        internal static string processSettingsTitle {
            get {
                return ResourceManager.GetString("processSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiniCoder برنامج الإنتاج.
        /// </summary>
        internal static string programTitle {
            get {
                return ResourceManager.GetString("programTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        internal static string saveButton {
            get {
                return ResourceManager.GetString("saveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الضبط.
        /// </summary>
        internal static string settingsTabTitle {
            get {
                return ResourceManager.GetString("settingsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .معدل البت المتغير للصوت يحدد جودة الصوت المخرجة\r\n.فكلما ازداد معدل البت زادت جودة الصوت.
        /// </summary>
        internal static string tooltipAudioBr {
            get {
                return ResourceManager.GetString("tooltipAudioBr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توضيحات حاليًا.
        /// </summary>
        internal static string tooltipContainer {
            get {
                return ResourceManager.GetString("tooltipContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخفيف التشويش يقوم بإزالة البيكسلات الحمراء والزرقاء\r\n.وغيرهما، التي تشوش على الفيديو.
        /// </summary>
        internal static string tooltipDenoise {
            get {
                return ResourceManager.GetString("tooltipDenoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توضيحات حاليًا.
        /// </summary>
        internal static string tooltipField {
            get {
                return ResourceManager.GetString("tooltipField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عند تحديديك لحجم الملف المخرج، سيقوم البرنامج بمحاولة\r\n.الحصول على حجم مقارب لما حددت.
        /// </summary>
        internal static string tooltipFileSize {
            get {
                return ResourceManager.GetString("tooltipFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .تحدد الجودة درجة وضوح الفيديو المنتج.
        /// </summary>
        internal static string tooltipQuality {
            get {
                return ResourceManager.GetString("tooltipQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ،باستخدام مرشح الأبعاد يمكنك تعديل أبعاد الفيديو المنتج\r\n.مع تنعيم الفيديو أو شحذه.
        /// </summary>
        internal static string tooltipResize {
            get {
                return ResourceManager.GetString("tooltipResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر ملف الترجمة.
        /// </summary>
        internal static string tooltipSub {
            get {
                return ResourceManager.GetString("tooltipSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معدل البت المتغير للفيديو يستخدم لتحديد أفضل جودة باستخدام أقل قيمة للمقسم\r\n.مع تناسب معدل البت المتغير. فكلما زاد معدل البت زادة جودة الفيديو.
        /// </summary>
        internal static string tooltipVideoBr {
            get {
                return ResourceManager.GetString("tooltipVideoBr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توضيحات حاليًا.
        /// </summary>
        internal static string tooltipVideoCodec {
            get {
                return ResourceManager.GetString("tooltipVideoCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض وارتفاع الفيديو المنتج.
        /// </summary>
        internal static string tooltipWidthHeight {
            get {
                return ResourceManager.GetString("tooltipWidthHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        internal static string updateCancelButton {
            get {
                return ResourceManager.GetString("updateCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث.
        /// </summary>
        internal static string updateColumn1 {
            get {
                return ResourceManager.GetString("updateColumn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        internal static string updateColumn2 {
            get {
                return ResourceManager.GetString("updateColumn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النسخة الحالية.
        /// </summary>
        internal static string updateColumn3 {
            get {
                return ResourceManager.GetString("updateColumn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أحدث نسخة.
        /// </summary>
        internal static string updateColumn4 {
            get {
                return ResourceManager.GetString("updateColumn4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        internal static string updateColumn5 {
            get {
                return ResourceManager.GetString("updateColumn5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخصيص الأماكن.
        /// </summary>
        internal static string updateCustomPath {
            get {
                return ResourceManager.GetString("updateCustomPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحديث متوفر. هل ترغب بالتحديث؟.
        /// </summary>
        internal static string updateMessage {
            get {
                return ResourceManager.GetString("updateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiniCoder مُحدث الـ.
        /// </summary>
        internal static string updaterTitle {
            get {
                return ResourceManager.GetString("updaterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث.
        /// </summary>
        internal static string updateUpdateButton {
            get {
                return ResourceManager.GetString("updateUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يتم الآن ضبط معدل الفريمات.
        /// </summary>
        internal static string vfrParsing {
            get {
                return ResourceManager.GetString("vfrParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أُلغي ضبط الفريمات.
        /// </summary>
        internal static string vfrParsingAborted {
            get {
                return ResourceManager.GetString("vfrParsingAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتهى ضبط الفريمات.
        /// </summary>
        internal static string vfrParsingCompleted {
            get {
                return ResourceManager.GetString("vfrParsingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :معدل البت.
        /// </summary>
        internal static string videoBitRate {
            get {
                return ResourceManager.GetString("videoBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :المرمز.
        /// </summary>
        internal static string videoCodec {
            get {
                return ResourceManager.GetString("videoCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :حجم الملف.
        /// </summary>
        internal static string videoFileSize {
            get {
                return ResourceManager.GetString("videoFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string videoOptionsTitle {
            get {
                return ResourceManager.GetString("videoOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :الجودة.
        /// </summary>
        internal static string videoQuality {
            get {
                return ResourceManager.GetString("videoQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوسطة;عالية;عالية جدًا;(عالية جدًا (أنيمي +50 مب;(عالية جدًا (أنيمي -50 مب;(عالية جدًا (برامج تلفزيونية\أفلام;CRF أنيمي;Ipod;PSP;PS3/XBOX.
        /// </summary>
        internal static string videoQualityOptions {
            get {
                return ResourceManager.GetString("videoQualityOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفيديو.
        /// </summary>
        internal static string videoTabTitle {
            get {
                return ResourceManager.GetString("videoTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عند الانتهاء.
        /// </summary>
        internal static string whenDone {
            get {
                return ResourceManager.GetString("whenDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا تفعل شيئًا;بيات;سكون;إيقاف التشغيل.
        /// </summary>
        internal static string whenDoneOptions {
            get {
                return ResourceManager.GetString("whenDoneOptions", resourceCulture);
            }
        }
    }
}
