//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniTech.MiniCoder.Core.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dutch {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dutch() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniTech.MiniCoder.Core.Languages.Dutch", typeof(Dutch).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicaties.
        /// </summary>
        internal static string applicationsButton {
            get {
                return ResourceManager.GetString("applicationsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitsnelheid:.
        /// </summary>
        internal static string audioBitrate {
            get {
                return ResourceManager.GetString("audioBitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codec:.
        /// </summary>
        internal static string audioCodec {
            get {
                return ResourceManager.GetString("audioCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezig met het decoderen van de audio.
        /// </summary>
        internal static string audioDecodingMessage {
            get {
                return ResourceManager.GetString("audioDecodingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezig met het encoderen van de audio naar.
        /// </summary>
        internal static string audioEncodingMessage {
            get {
                return ResourceManager.GetString("audioEncodingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio encoderen:.
        /// </summary>
        internal static string audioEncodingTrack {
            get {
                return ResourceManager.GetString("audioEncodingTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Opties.
        /// </summary>
        internal static string audioOptionsTitle {
            get {
                return ResourceManager.GetString("audioOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string audioTabTitle {
            get {
                return ResourceManager.GetString("audioTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formaat:.
        /// </summary>
        internal static string containerFormat {
            get {
                return ResourceManager.GetString("containerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        internal static string containerOptionsTitle {
            get {
                return ResourceManager.GetString("containerOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kern.
        /// </summary>
        internal static string coreTabTitle {
            get {
                return ResourceManager.GetString("coreTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persoonlijk.
        /// </summary>
        internal static string customButton {
            get {
                return ResourceManager.GetString("customButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuleer.
        /// </summary>
        internal static string customFilterCancel {
            get {
                return ResourceManager.GetString("customFilterCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als je de default filters wilt uitschakelen, gebruik dan de Instellingen tab..
        /// </summary>
        internal static string customFilterNote {
            get {
                return ResourceManager.GetString("customFilterNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string customFilterOK {
            get {
                return ResourceManager.GetString("customFilterOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voer hier je persoonlijke AviSynth filters in..
        /// </summary>
        internal static string customFilterText {
            get {
                return ResourceManager.GetString("customFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persoonlijke Filters.
        /// </summary>
        internal static string customFilterTitle {
            get {
                return ResourceManager.GetString("customFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persoonlijke Locaties.
        /// </summary>
        internal static string customPathsTitle {
            get {
                return ResourceManager.GetString("customPathsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demuxen geannuleerd.
        /// </summary>
        internal static string demuxingAbortedMessage {
            get {
                return ResourceManager.GetString("demuxingAbortedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demuxen compleet.
        /// </summary>
        internal static string demuxingCompleteMessage {
            get {
                return ResourceManager.GetString("demuxingCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezig met het demuxen van de.
        /// </summary>
        internal static string demuxingMessage {
            get {
                return ResourceManager.GetString("demuxingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezig met het demuxen van het  MKV bestand.
        /// </summary>
        internal static string demuxingMkv {
            get {
                return ResourceManager.GetString("demuxingMkv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ophalen MKV Bijlagen.
        /// </summary>
        internal static string demuxingMkvAttachments {
            get {
                return ResourceManager.GetString("demuxingMkvAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ophalen MKV Hoofdstukken.
        /// </summary>
        internal static string demuxingMkvChapters {
            get {
                return ResourceManager.GetString("demuxingMkvChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezig met het demuxen van de MP4 Audio.
        /// </summary>
        internal static string demuxingmp4Audio {
            get {
                return ResourceManager.GetString("demuxingmp4Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezig met het demuxen van de MP4 video.
        /// </summary>
        internal static string demuxingmp4Video {
            get {
                return ResourceManager.GetString("demuxingmp4Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezig met het indexeren van het VOB bestand.
        /// </summary>
        internal static string demuxingVob {
            get {
                return ResourceManager.GetString("demuxingVob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoofdstukken aan het ophalen.
        /// </summary>
        internal static string demuxingvobChapters {
            get {
                return ResourceManager.GetString("demuxingvobChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ondertitelingen aan het ophalen.
        /// </summary>
        internal static string demuxingvobSubs {
            get {
                return ResourceManager.GetString("demuxingvobSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string encodeStartButton {
            get {
                return ResourceManager.GetString("encodeStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string encodeStopButton {
            get {
                return ResourceManager.GetString("encodeStopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klaar met converteren.
        /// </summary>
        internal static string encodingComplete {
            get {
                return ResourceManager.GetString("encodingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negeer Bijlagen.
        /// </summary>
        internal static string encodingIgnoreAttachments {
            get {
                return ResourceManager.GetString("encodingIgnoreAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negeer Audio.
        /// </summary>
        internal static string encodingIgnoreAudio {
            get {
                return ResourceManager.GetString("encodingIgnoreAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negeer Hoofdstukken.
        /// </summary>
        internal static string encodingIgnoreChapters {
            get {
                return ResourceManager.GetString("encodingIgnoreChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negeer ondertitels.
        /// </summary>
        internal static string encodingIgnoreSubs {
            get {
                return ResourceManager.GetString("encodingIgnoreSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ga naar het volgend bestand bij errors.
        /// </summary>
        internal static string encodingNextError {
            get {
                return ResourceManager.GetString("encodingNextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon video preview (Enkel voor debuggen).
        /// </summary>
        internal static string encodingShowVideoPreview {
            get {
                return ResourceManager.GetString("encodingShowVideoPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codering.
        /// </summary>
        internal static string encodingTitle {
            get {
                return ResourceManager.GetString("encodingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Converteren.
        /// </summary>
        internal static string encodingVideoPass {
            get {
                return ResourceManager.GetString("encodingVideoPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezig met converteren naar Theora.
        /// </summary>
        internal static string encodingVideoTheora {
            get {
                return ResourceManager.GetString("encodingVideoTheora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er heeft zich een error plaatsgevonden. Wilt U een rapport verzenden?.
        /// </summary>
        internal static string errorWarningMessage {
            get {
                return ResourceManager.GetString("errorWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string errorWarningTitle {
            get {
                return ResourceManager.GetString("errorWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestandsinformatie aan het ophalen.
        /// </summary>
        internal static string fileInfoFetch {
            get {
                return ResourceManager.GetString("fileInfoFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Opties.
        /// </summary>
        internal static string filterOptionsTitle {
            get {
                return ResourceManager.GetString("filterOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezig met de indexering van AVC.
        /// </summary>
        internal static string indexingAvc {
            get {
                return ResourceManager.GetString("indexingAvc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexering geannuleerd.
        /// </summary>
        internal static string indexingAvcAbort {
            get {
                return ResourceManager.GetString("indexingAvcAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexering compleet.
        /// </summary>
        internal static string indexingAvcCompleted {
            get {
                return ResourceManager.GetString("indexingAvcCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUI klaar.
        /// </summary>
        internal static string infoLabel {
            get {
                return ResourceManager.GetString("infoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestand (Markeer als het bestand VFR is).
        /// </summary>
        internal static string inputColumn1Title {
            get {
                return ResourceManager.GetString("inputColumn1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geannuleerd.
        /// </summary>
        internal static string inputColumn2StatusAborted {
            get {
                return ResourceManager.GetString("inputColumn2StatusAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geconverteerd.
        /// </summary>
        internal static string inputColumn2StatusDone {
            get {
                return ResourceManager.GetString("inputColumn2StatusDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezig.
        /// </summary>
        internal static string inputColumn2StatusEncoding {
            get {
                return ResourceManager.GetString("inputColumn2StatusEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string inputColumn2StatusError {
            get {
                return ResourceManager.GetString("inputColumn2StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klaar.
        /// </summary>
        internal static string inputColumn2StatusReady {
            get {
                return ResourceManager.GetString("inputColumn2StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string inputColumn2StatusTitle {
            get {
                return ResourceManager.GetString("inputColumn2StatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoer.
        /// </summary>
        internal static string inputTabTitle {
            get {
                return ResourceManager.GetString("inputTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiëren.
        /// </summary>
        internal static string logMenuCopy {
            get {
                return ResourceManager.GetString("logMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verstuur error rapport.
        /// </summary>
        internal static string logMenuSend {
            get {
                return ResourceManager.GetString("logMenuSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logboek.
        /// </summary>
        internal static string logTabTitle {
            get {
                return ResourceManager.GetString("logTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toevoegen.
        /// </summary>
        internal static string menuAdd {
            get {
                return ResourceManager.GetString("menuAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alles verwijderen.
        /// </summary>
        internal static string menuClear {
            get {
                return ResourceManager.GetString("menuClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijder.
        /// </summary>
        internal static string menuRemove {
            get {
                return ResourceManager.GetString("menuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporteren naar.
        /// </summary>
        internal static string muxingMessage {
            get {
                return ResourceManager.GetString("muxingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muxen/Demuxen.
        /// </summary>
        internal static string muxingTabTitle {
            get {
                return ResourceManager.GetString("muxingTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuws.
        /// </summary>
        internal static string newsTabTitle {
            get {
                return ResourceManager.GetString("newsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opties.
        /// </summary>
        internal static string optionsTabTitle {
            get {
                return ResourceManager.GetString("optionsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andere.
        /// </summary>
        internal static string otherTabTitle {
            get {
                return ResourceManager.GetString("otherTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitvoer:.
        /// </summary>
        internal static string outputDirectory {
            get {
                return ResourceManager.GetString("outputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schakel video titel reclame uit.
        /// </summary>
        internal static string outputDisableVideoAdvert {
            get {
                return ResourceManager.GetString("outputDisableVideoAdvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitvoer Instellingen.
        /// </summary>
        internal static string outputSettingsTitle {
            get {
                return ResourceManager.GetString("outputSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        internal static string pluginsTabTitle {
            get {
                return ResourceManager.GetString("pluginsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruisverw.:.
        /// </summary>
        internal static string postDenoiser {
            get {
                return ResourceManager.GetString("postDenoiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen;Licht;Medium;Zwaar;Gestoord.
        /// </summary>
        internal static string postDenoiserOptions {
            get {
                return ResourceManager.GetString("postDenoiserOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naverwerking:.
        /// </summary>
        internal static string postprocessingOptionsTitle {
            get {
                return ResourceManager.GetString("postprocessingOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verscherp:.
        /// </summary>
        internal static string postSharpen {
            get {
                return ResourceManager.GetString("postSharpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen;Licht;Medium;Zwaar;Gestoord.
        /// </summary>
        internal static string postSharpenOptions {
            get {
                return ResourceManager.GetString("postSharpenOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ondertitel:.
        /// </summary>
        internal static string postSubtitle {
            get {
                return ResourceManager.GetString("postSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veld:.
        /// </summary>
        internal static string preField {
            get {
                return ResourceManager.GetString("preField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorverwerking.
        /// </summary>
        internal static string preprocessingOptionsTitle {
            get {
                return ResourceManager.GetString("preprocessingOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herschalen:.
        /// </summary>
        internal static string preResize {
            get {
                return ResourceManager.GetString("preResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niet;Zacht;Neutraal;Scherp;Heel Scherp (Lanczos64);Heel Scherp (Spline36).
        /// </summary>
        internal static string preResizeOptions {
            get {
                return ResourceManager.GetString("preResizeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breedte/Hoogte.
        /// </summary>
        internal static string preWidthHeight {
            get {
                return ResourceManager.GetString("preWidthHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioriteit:.
        /// </summary>
        internal static string processPriority {
            get {
                return ResourceManager.GetString("processPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laag;Onder Normaal;Normaal;Boven Normaal;Hoog;Realtime.
        /// </summary>
        internal static string processPriorityOptions {
            get {
                return ResourceManager.GetString("processPriorityOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesinstellingen.
        /// </summary>
        internal static string processSettingsTitle {
            get {
                return ResourceManager.GetString("processSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiniCoder.
        /// </summary>
        internal static string programTitle {
            get {
                return ResourceManager.GetString("programTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan.
        /// </summary>
        internal static string saveButton {
            get {
                return ResourceManager.GetString("saveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instellingen.
        /// </summary>
        internal static string settingsTabTitle {
            get {
                return ResourceManager.GetString("settingsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Audio Bitrate determines the quality of the audio output.\r\nThe higher the bitrate the better the quality.\r\nRecommended: Minimum 32 Kbps.
        /// </summary>
        internal static string tooltipAudioBr {
            get {
                return ResourceManager.GetString("tooltipAudioBr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both audio codecs provide high quality at low bitrates.\r\nRecommended: Nero AAC&quot;.
        /// </summary>
        internal static string tooltipAudioCodec {
            get {
                return ResourceManager.GetString("tooltipAudioCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matroska: \r\nThe Matroska Multimedia Container is an open standard free container format, a file\r\nformat that can hold an unlimited number of video, audio, picture or subtitle tracks\r\n inside a single file.\r\nMP4:\r\nIt is a multimedia container format standard specified as a part of MPEG-4. It is most\r\ncommonly used to store digital audio and digital video streams, especially those defined\r\n by MPEG..
        /// </summary>
        internal static string tooltipContainer {
            get {
                return ResourceManager.GetString("tooltipContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video denoising is the process of removing noise\r\nfrom a video signal..
        /// </summary>
        internal static string tooltipDenoise {
            get {
                return ResourceManager.GetString("tooltipDenoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldDeinterlace: \r\nThis filter provides functionality similar to the postprocessing function \r\nof Telecide. You can use it for pure interlaced streams.
        /// </summary>
        internal static string tooltipField {
            get {
                return ResourceManager.GetString("tooltipField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target File Size means that the program will try to get the\r\noutput filesize as close as it can to the determined size.\r\nThings that could make the output bigger than set:\r\n- Attachments (Some fonts take over 5mb)\r\n- VFR (Variable FrameRate)\r\nRecommended\r\n- Minimum 50 mb for 20 min anime\r\n- Minimum 120 mb for TV-Show\r\n- Minmum 300mb for a Movie.
        /// </summary>
        internal static string tooltipFileSize {
            get {
                return ResourceManager.GetString("tooltipFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The higher the quality, the slower the encoding time.
        /// </summary>
        internal static string tooltipQuality {
            get {
                return ResourceManager.GetString("tooltipQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With a resizing filter you can easily resize a video to a \r\n preferred aspect ratio. Using these filters you can either \r\nsoften the image or sharpen it..
        /// </summary>
        internal static string tooltipResize {
            get {
                return ResourceManager.GetString("tooltipResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer een ondertitel die je wil toevoegen aan de video (Hardsub).
        /// </summary>
        internal static string tooltipSub {
            get {
                return ResourceManager.GetString("tooltipSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average (Variabele) Bit Rate is used to determine the best quality at the lowest possible quantizizer \r\nwhile maintaining the average bit rate. The higher the bitrate, the better the output quality. .
        /// </summary>
        internal static string tooltipVideoBr {
            get {
                return ResourceManager.GetString("tooltipVideoBr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X264: It is a free software library for encoding video streams \r\ninto the H.264/MPEG-4 AVC format.\r\n\r\nXvid (formerly &quot;XviD&quot;) is a video codec library following the MPEG-4 standard,\r\n specifically MPEG-4 Part 2 Advanced Simple Profile (ASP). It uses ASP \r\n features..
        /// </summary>
        internal static string tooltipVideoCodec {
            get {
                return ResourceManager.GetString("tooltipVideoCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width and heigth of the re-encoded video..
        /// </summary>
        internal static string tooltipWidthHeight {
            get {
                return ResourceManager.GetString("tooltipWidthHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuleer.
        /// </summary>
        internal static string updateCancelButton {
            get {
                return ResourceManager.GetString("updateCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bijwerken.
        /// </summary>
        internal static string updateColumn1 {
            get {
                return ResourceManager.GetString("updateColumn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        internal static string updateColumn2 {
            get {
                return ResourceManager.GetString("updateColumn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestaande Versie.
        /// </summary>
        internal static string updateColumn3 {
            get {
                return ResourceManager.GetString("updateColumn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laatste Versie.
        /// </summary>
        internal static string updateColumn4 {
            get {
                return ResourceManager.GetString("updateColumn4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string updateColumn5 {
            get {
                return ResourceManager.GetString("updateColumn5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persoonlijke Locaties.
        /// </summary>
        internal static string updateCustomPath {
            get {
                return ResourceManager.GetString("updateCustomPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn updates gevonden.Wilt u deze nu downloaden?.
        /// </summary>
        internal static string updateMessage {
            get {
                return ResourceManager.GetString("updateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiniCoder Updater.
        /// </summary>
        internal static string updaterTitle {
            get {
                return ResourceManager.GetString("updaterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bijwerken.
        /// </summary>
        internal static string updateUpdateButton {
            get {
                return ResourceManager.GetString("updateUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VFR Analyseren.
        /// </summary>
        internal static string vfrParsing {
            get {
                return ResourceManager.GetString("vfrParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse geannuleerd.
        /// </summary>
        internal static string vfrParsingAborted {
            get {
                return ResourceManager.GetString("vfrParsingAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse compleet.
        /// </summary>
        internal static string vfrParsingCompleted {
            get {
                return ResourceManager.GetString("vfrParsingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitsnelheid:.
        /// </summary>
        internal static string videoBitRate {
            get {
                return ResourceManager.GetString("videoBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codec:.
        /// </summary>
        internal static string videoCodec {
            get {
                return ResourceManager.GetString("videoCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grootte:.
        /// </summary>
        internal static string videoFileSize {
            get {
                return ResourceManager.GetString("videoFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Opties.
        /// </summary>
        internal static string videoOptionsTitle {
            get {
                return ResourceManager.GetString("videoOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwaliteit:.
        /// </summary>
        internal static string videoQuality {
            get {
                return ResourceManager.GetString("videoQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium;Hoog;Heel Hoog;Heel Hoog (+50mb anime);Heel Hoog (-50mb anime);Heel Hoog (TV-Series/Films);CRF (Anime);Ipod;PSP;PS3/XBOX.
        /// </summary>
        internal static string videoQualityOptions {
            get {
                return ResourceManager.GetString("videoQualityOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string videoTabTitle {
            get {
                return ResourceManager.GetString("videoTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanneer klaar:.
        /// </summary>
        internal static string whenDone {
            get {
                return ResourceManager.GetString("whenDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doe Niets;Slaapstand;Standby;Afsluiten.
        /// </summary>
        internal static string whenDoneOptions {
            get {
                return ResourceManager.GetString("whenDoneOptions", resourceCulture);
            }
        }
    }
}
