//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniCoder.Core.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniCoder.Core.Languages.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string applicationsButton {
            get {
                return ResourceManager.GetString("applicationsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit Rate:.
        /// </summary>
        internal static string audioBitrate {
            get {
                return ResourceManager.GetString("audioBitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codec:.
        /// </summary>
        internal static string audioCodec {
            get {
                return ResourceManager.GetString("audioCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoding Audio.
        /// </summary>
        internal static string audioDecodingMessage {
            get {
                return ResourceManager.GetString("audioDecodingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding audio to.
        /// </summary>
        internal static string audioEncodingMessage {
            get {
                return ResourceManager.GetString("audioEncodingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding Audio Track.
        /// </summary>
        internal static string audioEncodingTrack {
            get {
                return ResourceManager.GetString("audioEncodingTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Options.
        /// </summary>
        internal static string audioOptionsTitle {
            get {
                return ResourceManager.GetString("audioOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string audioTabTitle {
            get {
                return ResourceManager.GetString("audioTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        internal static string containerFormat {
            get {
                return ResourceManager.GetString("containerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        internal static string containerOptionsTitle {
            get {
                return ResourceManager.GetString("containerOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        internal static string coreTabTitle {
            get {
                return ResourceManager.GetString("coreTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string customButton {
            get {
                return ResourceManager.GetString("customButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string customFilterCancel {
            get {
                return ResourceManager.GetString("customFilterCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to disable a default filter disable it in the Settings Page..
        /// </summary>
        internal static string customFilterNote {
            get {
                return ResourceManager.GetString("customFilterNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string customFilterOK {
            get {
                return ResourceManager.GetString("customFilterOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Custom Avisynth Filters.
        /// </summary>
        internal static string customFilterText {
            get {
                return ResourceManager.GetString("customFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Filters.
        /// </summary>
        internal static string customFilterTitle {
            get {
                return ResourceManager.GetString("customFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Paths.
        /// </summary>
        internal static string customPathsTitle {
            get {
                return ResourceManager.GetString("customPathsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demuxing Aborted.
        /// </summary>
        internal static string demuxingAbortedMessage {
            get {
                return ResourceManager.GetString("demuxingAbortedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demuxing Completed.
        /// </summary>
        internal static string demuxingCompleteMessage {
            get {
                return ResourceManager.GetString("demuxingCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demuxing.
        /// </summary>
        internal static string demuxingMessage {
            get {
                return ResourceManager.GetString("demuxingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demuxing MKV Tracks.
        /// </summary>
        internal static string demuxingMkv {
            get {
                return ResourceManager.GetString("demuxingMkv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demuxing Attachments.
        /// </summary>
        internal static string demuxingMkvAttachments {
            get {
                return ResourceManager.GetString("demuxingMkvAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demuxing Chapters.
        /// </summary>
        internal static string demuxingMkvChapters {
            get {
                return ResourceManager.GetString("demuxingMkvChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demuxing MP4 Audio Track.
        /// </summary>
        internal static string demuxingmp4Audio {
            get {
                return ResourceManager.GetString("demuxingmp4Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demuxing MP4 Video Track.
        /// </summary>
        internal static string demuxingmp4Video {
            get {
                return ResourceManager.GetString("demuxingmp4Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started indexing VOB files.
        /// </summary>
        internal static string demuxingVob {
            get {
                return ResourceManager.GetString("demuxingVob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started fetching chapters..
        /// </summary>
        internal static string demuxingvobChapters {
            get {
                return ResourceManager.GetString("demuxingvobChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started fetching subs..
        /// </summary>
        internal static string demuxingvobSubs {
            get {
                return ResourceManager.GetString("demuxingvobSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string encodeStartButton {
            get {
                return ResourceManager.GetString("encodeStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string encodeStopButton {
            get {
                return ResourceManager.GetString("encodeStopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding Completed.
        /// </summary>
        internal static string encodingComplete {
            get {
                return ResourceManager.GetString("encodingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Attachments.
        /// </summary>
        internal static string encodingIgnoreAttachments {
            get {
                return ResourceManager.GetString("encodingIgnoreAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Audio.
        /// </summary>
        internal static string encodingIgnoreAudio {
            get {
                return ResourceManager.GetString("encodingIgnoreAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Chapters.
        /// </summary>
        internal static string encodingIgnoreChapters {
            get {
                return ResourceManager.GetString("encodingIgnoreChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Subs.
        /// </summary>
        internal static string encodingIgnoreSubs {
            get {
                return ResourceManager.GetString("encodingIgnoreSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to next file after error.
        /// </summary>
        internal static string encodingNextError {
            get {
                return ResourceManager.GetString("encodingNextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show video preview (Debug Only).
        /// </summary>
        internal static string encodingShowVideoPreview {
            get {
                return ResourceManager.GetString("encodingShowVideoPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        internal static string encodingTitle {
            get {
                return ResourceManager.GetString("encodingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding video.
        /// </summary>
        internal static string encodingVideoPass {
            get {
                return ResourceManager.GetString("encodingVideoPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding Theora video.
        /// </summary>
        internal static string encodingVideoTheora {
            get {
                return ResourceManager.GetString("encodingVideoTheora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems an error happend! Do you want to send an errorreport?.
        /// </summary>
        internal static string errorWarningMessage {
            get {
                return ResourceManager.GetString("errorWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string errorWarningTitle {
            get {
                return ResourceManager.GetString("errorWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching File Info.
        /// </summary>
        internal static string fileInfoFetch {
            get {
                return ResourceManager.GetString("fileInfoFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Options.
        /// </summary>
        internal static string filterOptionsTitle {
            get {
                return ResourceManager.GetString("filterOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexing AVC.
        /// </summary>
        internal static string indexingAvc {
            get {
                return ResourceManager.GetString("indexingAvc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexing Aborted.
        /// </summary>
        internal static string indexingAvcAbort {
            get {
                return ResourceManager.GetString("indexingAvcAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexing AVC Completed.
        /// </summary>
        internal static string indexingAvcCompleted {
            get {
                return ResourceManager.GetString("indexingAvcCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUI Ready.
        /// </summary>
        internal static string infoLabel {
            get {
                return ResourceManager.GetString("infoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input (Mark if file is VFR).
        /// </summary>
        internal static string inputColumn1Title {
            get {
                return ResourceManager.GetString("inputColumn1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        internal static string inputColumn2StatusAborted {
            get {
                return ResourceManager.GetString("inputColumn2StatusAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string inputColumn2StatusDone {
            get {
                return ResourceManager.GetString("inputColumn2StatusDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        internal static string inputColumn2StatusEncoding {
            get {
                return ResourceManager.GetString("inputColumn2StatusEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string inputColumn2StatusError {
            get {
                return ResourceManager.GetString("inputColumn2StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string inputColumn2StatusReady {
            get {
                return ResourceManager.GetString("inputColumn2StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string inputColumn2StatusTitle {
            get {
                return ResourceManager.GetString("inputColumn2StatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string inputTabTitle {
            get {
                return ResourceManager.GetString("inputTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string logMenuCopy {
            get {
                return ResourceManager.GetString("logMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send error report.
        /// </summary>
        internal static string logMenuSend {
            get {
                return ResourceManager.GetString("logMenuSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string logTabTitle {
            get {
                return ResourceManager.GetString("logTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string menuAdd {
            get {
                return ResourceManager.GetString("menuAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string menuClear {
            get {
                return ResourceManager.GetString("menuClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string menuRemove {
            get {
                return ResourceManager.GetString("menuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muxing to.
        /// </summary>
        internal static string muxingMessage {
            get {
                return ResourceManager.GetString("muxingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muxing/Demuxing.
        /// </summary>
        internal static string muxingTabTitle {
            get {
                return ResourceManager.GetString("muxingTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string newsTabTitle {
            get {
                return ResourceManager.GetString("newsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string optionsTabTitle {
            get {
                return ResourceManager.GetString("optionsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string otherTabTitle {
            get {
                return ResourceManager.GetString("otherTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Dir.:.
        /// </summary>
        internal static string outputDirectory {
            get {
                return ResourceManager.GetString("outputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable video title advert.
        /// </summary>
        internal static string outputDisableVideoAdvert {
            get {
                return ResourceManager.GetString("outputDisableVideoAdvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Settings.
        /// </summary>
        internal static string outputSettingsTitle {
            get {
                return ResourceManager.GetString("outputSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        internal static string pluginsTabTitle {
            get {
                return ResourceManager.GetString("pluginsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denoiser:.
        /// </summary>
        internal static string postDenoiser {
            get {
                return ResourceManager.GetString("postDenoiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None;Light;Medium;Heavy;Insane.
        /// </summary>
        internal static string postDenoiserOptions {
            get {
                return ResourceManager.GetString("postDenoiserOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Processing.
        /// </summary>
        internal static string postprocessingOptionsTitle {
            get {
                return ResourceManager.GetString("postprocessingOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpen:.
        /// </summary>
        internal static string postSharpen {
            get {
                return ResourceManager.GetString("postSharpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None;Light;Medium;Heavy;Insane.
        /// </summary>
        internal static string postSharpenOptions {
            get {
                return ResourceManager.GetString("postSharpenOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle:.
        /// </summary>
        internal static string postSubtitle {
            get {
                return ResourceManager.GetString("postSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field:.
        /// </summary>
        internal static string preField {
            get {
                return ResourceManager.GetString("preField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Processing.
        /// </summary>
        internal static string preprocessingOptionsTitle {
            get {
                return ResourceManager.GetString("preprocessingOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize:.
        /// </summary>
        internal static string preResize {
            get {
                return ResourceManager.GetString("preResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None;Soft;Neutral;Sharp;Very Sharp (Lanczos64);Very Sharp (Spline36).
        /// </summary>
        internal static string preResizeOptions {
            get {
                return ResourceManager.GetString("preResizeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width/Height:.
        /// </summary>
        internal static string preWidthHeight {
            get {
                return ResourceManager.GetString("preWidthHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority:.
        /// </summary>
        internal static string processPriority {
            get {
                return ResourceManager.GetString("processPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low;Below Normal;Normal;Above Normal;High;Realtime.
        /// </summary>
        internal static string processPriorityOptions {
            get {
                return ResourceManager.GetString("processPriorityOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Settings.
        /// </summary>
        internal static string processSettingsTitle {
            get {
                return ResourceManager.GetString("processSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiniCoder Encoding GUI.
        /// </summary>
        internal static string programTitle {
            get {
                return ResourceManager.GetString("programTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string saveButton {
            get {
                return ResourceManager.GetString("saveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settingsTabTitle {
            get {
                return ResourceManager.GetString("settingsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Audio Bitrate determines the quality of the audio output.\r\nThe higher the bitrate the better the quality..
        /// </summary>
        internal static string tooltipAudioBr {
            get {
                return ResourceManager.GetString("tooltipAudioBr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tooltip yet.
        /// </summary>
        internal static string tooltipContainer {
            get {
                return ResourceManager.GetString("tooltipContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video denoising is the process of removing noise \r\nfrom a video signal.
        /// </summary>
        internal static string tooltipDenoise {
            get {
                return ResourceManager.GetString("tooltipDenoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tooltip yet.
        /// </summary>
        internal static string tooltipField {
            get {
                return ResourceManager.GetString("tooltipField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target File Size means that the program will try to get the \r\n output filesize as close as it can to the determined size..
        /// </summary>
        internal static string tooltipFileSize {
            get {
                return ResourceManager.GetString("tooltipFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality determines the video quality of the outputted file..
        /// </summary>
        internal static string tooltipQuality {
            get {
                return ResourceManager.GetString("tooltipQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With a resizing filter you can easily resize a video to a \r\n preferred aspect ratio. Using these filters you can either\r\nsoften the image or sharpen it..
        /// </summary>
        internal static string tooltipResize {
            get {
                return ResourceManager.GetString("tooltipResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Subtitle file to use.
        /// </summary>
        internal static string tooltipSub {
            get {
                return ResourceManager.GetString("tooltipSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average (Variable) Bit Rate is used to determine the best quality at the lowest possible quantizizer \r\n while maintaining the average bit rate. The higher the bitrate, the better the output quality. .
        /// </summary>
        internal static string tooltipVideoBr {
            get {
                return ResourceManager.GetString("tooltipVideoBr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tooltip yet.
        /// </summary>
        internal static string tooltipVideoCodec {
            get {
                return ResourceManager.GetString("tooltipVideoCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width and heigth of the re-encoded video..
        /// </summary>
        internal static string tooltipWidthHeight {
            get {
                return ResourceManager.GetString("tooltipWidthHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string updateCancelButton {
            get {
                return ResourceManager.GetString("updateCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string updateColumn1 {
            get {
                return ResourceManager.GetString("updateColumn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string updateColumn2 {
            get {
                return ResourceManager.GetString("updateColumn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Version.
        /// </summary>
        internal static string updateColumn3 {
            get {
                return ResourceManager.GetString("updateColumn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Version.
        /// </summary>
        internal static string updateColumn4 {
            get {
                return ResourceManager.GetString("updateColumn4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string updateColumn5 {
            get {
                return ResourceManager.GetString("updateColumn5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Paths.
        /// </summary>
        internal static string updateCustomPath {
            get {
                return ResourceManager.GetString("updateCustomPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates available. Do you wish to download them now?.
        /// </summary>
        internal static string updateMessage {
            get {
                return ResourceManager.GetString("updateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiniCoder Updater.
        /// </summary>
        internal static string updaterTitle {
            get {
                return ResourceManager.GetString("updaterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string updateUpdateButton {
            get {
                return ResourceManager.GetString("updateUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing VFR.
        /// </summary>
        internal static string vfrParsing {
            get {
                return ResourceManager.GetString("vfrParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted Parsing VFR.
        /// </summary>
        internal static string vfrParsingAborted {
            get {
                return ResourceManager.GetString("vfrParsingAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Parsing VFR.
        /// </summary>
        internal static string vfrParsingCompleted {
            get {
                return ResourceManager.GetString("vfrParsingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit Rate:.
        /// </summary>
        internal static string videoBitRate {
            get {
                return ResourceManager.GetString("videoBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codec:.
        /// </summary>
        internal static string videoCodec {
            get {
                return ResourceManager.GetString("videoCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size:.
        /// </summary>
        internal static string videoFileSize {
            get {
                return ResourceManager.GetString("videoFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Options.
        /// </summary>
        internal static string videoOptionsTitle {
            get {
                return ResourceManager.GetString("videoOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality:.
        /// </summary>
        internal static string videoQuality {
            get {
                return ResourceManager.GetString("videoQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium;High;Very High;Very High (+50mb anime);Very High (-50mb anime);Very High (TV-Shows/Movies);CRF (Anime);Ipod;PSP;PS3/XBOX.
        /// </summary>
        internal static string videoQualityOptions {
            get {
                return ResourceManager.GetString("videoQualityOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string videoTabTitle {
            get {
                return ResourceManager.GetString("videoTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When done.
        /// </summary>
        internal static string whenDone {
            get {
                return ResourceManager.GetString("whenDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Nothing;Hibernate;Standby;Shutdown.
        /// </summary>
        internal static string whenDoneOptions {
            get {
                return ResourceManager.GetString("whenDoneOptions", resourceCulture);
            }
        }
    }
}
