//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniCoder.Core.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniCoder.Core.Languages.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string applicationsButton {
            get {
                return ResourceManager.GetString("applicationsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit Rate:.
        /// </summary>
        internal static string audioBitrate {
            get {
                return ResourceManager.GetString("audioBitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codec:.
        /// </summary>
        internal static string audioCodec {
            get {
                return ResourceManager.GetString("audioCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Options.
        /// </summary>
        internal static string audioOptionsTitle {
            get {
                return ResourceManager.GetString("audioOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        internal static string containerFormat {
            get {
                return ResourceManager.GetString("containerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        internal static string containerOptionsTitle {
            get {
                return ResourceManager.GetString("containerOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string customButton {
            get {
                return ResourceManager.GetString("customButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string customFilterCancel {
            get {
                return ResourceManager.GetString("customFilterCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to disable a default filter disable it in the Settings Page..
        /// </summary>
        internal static string customFilterNote {
            get {
                return ResourceManager.GetString("customFilterNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string customFilterOK {
            get {
                return ResourceManager.GetString("customFilterOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Custom Avisynth Filters.
        /// </summary>
        internal static string customFilterText {
            get {
                return ResourceManager.GetString("customFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Filters.
        /// </summary>
        internal static string customFilterTitle {
            get {
                return ResourceManager.GetString("customFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string encodeStartButton {
            get {
                return ResourceManager.GetString("encodeStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string encodeStopButton {
            get {
                return ResourceManager.GetString("encodeStopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Attachments.
        /// </summary>
        internal static string encodingIgnoreAttachments {
            get {
                return ResourceManager.GetString("encodingIgnoreAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Audio.
        /// </summary>
        internal static string encodingIgnoreAudio {
            get {
                return ResourceManager.GetString("encodingIgnoreAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Chapters.
        /// </summary>
        internal static string encodingIgnoreChapters {
            get {
                return ResourceManager.GetString("encodingIgnoreChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Subs.
        /// </summary>
        internal static string encodingIgnoreSubs {
            get {
                return ResourceManager.GetString("encodingIgnoreSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to next file after error.
        /// </summary>
        internal static string encodingNextError {
            get {
                return ResourceManager.GetString("encodingNextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show video preview (Debug Only).
        /// </summary>
        internal static string encodingShowVideoPreview {
            get {
                return ResourceManager.GetString("encodingShowVideoPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        internal static string encodingTitle {
            get {
                return ResourceManager.GetString("encodingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Options.
        /// </summary>
        internal static string filterOptionsTitle {
            get {
                return ResourceManager.GetString("filterOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUI Ready.
        /// </summary>
        internal static string infoLabel {
            get {
                return ResourceManager.GetString("infoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input (Mark if file is VFR).
        /// </summary>
        internal static string inputColumn1Title {
            get {
                return ResourceManager.GetString("inputColumn1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        internal static string inputColumn2StatusEncoding {
            get {
                return ResourceManager.GetString("inputColumn2StatusEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string inputColumn2StatusError {
            get {
                return ResourceManager.GetString("inputColumn2StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string inputColumn2StatusReady {
            get {
                return ResourceManager.GetString("inputColumn2StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string inputColumn2StatusTitle {
            get {
                return ResourceManager.GetString("inputColumn2StatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string inputTabTitle {
            get {
                return ResourceManager.GetString("inputTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string logTabTitle {
            get {
                return ResourceManager.GetString("logTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string newsTabTitle {
            get {
                return ResourceManager.GetString("newsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string optionsTabTitle {
            get {
                return ResourceManager.GetString("optionsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Dir.:.
        /// </summary>
        internal static string outputDirectory {
            get {
                return ResourceManager.GetString("outputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable video title advert.
        /// </summary>
        internal static string outputDisableVideoAdvert {
            get {
                return ResourceManager.GetString("outputDisableVideoAdvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Settings.
        /// </summary>
        internal static string outputSettingsTitle {
            get {
                return ResourceManager.GetString("outputSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denoiser:.
        /// </summary>
        internal static string postDenoiser {
            get {
                return ResourceManager.GetString("postDenoiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None;Light;Medium;Heavy;Insane.
        /// </summary>
        internal static string postDenoiserOptions {
            get {
                return ResourceManager.GetString("postDenoiserOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Processing.
        /// </summary>
        internal static string postprocessingOptionsTitle {
            get {
                return ResourceManager.GetString("postprocessingOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpen:.
        /// </summary>
        internal static string postSharpen {
            get {
                return ResourceManager.GetString("postSharpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None;Light;Medium;Heavy;Insane.
        /// </summary>
        internal static string postSharpenOptions {
            get {
                return ResourceManager.GetString("postSharpenOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle.
        /// </summary>
        internal static string postSubtitle {
            get {
                return ResourceManager.GetString("postSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field:.
        /// </summary>
        internal static string preField {
            get {
                return ResourceManager.GetString("preField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Processing.
        /// </summary>
        internal static string preprocessingOptionsTitle {
            get {
                return ResourceManager.GetString("preprocessingOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize:.
        /// </summary>
        internal static string preResize {
            get {
                return ResourceManager.GetString("preResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None;Soft;Neutral;Sharp;Very Sharp (Lanczos64);Very Sharp (Spline36).
        /// </summary>
        internal static string preResizeOptions {
            get {
                return ResourceManager.GetString("preResizeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width/Height:.
        /// </summary>
        internal static string preWidthHeight {
            get {
                return ResourceManager.GetString("preWidthHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority:.
        /// </summary>
        internal static string processPriority {
            get {
                return ResourceManager.GetString("processPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low;Below Normal;Normal;Above Normal;High;Realtime.
        /// </summary>
        internal static string processPriorityOptions {
            get {
                return ResourceManager.GetString("processPriorityOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Settings.
        /// </summary>
        internal static string processSettingsTitle {
            get {
                return ResourceManager.GetString("processSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiniCoder Encoding GUI.
        /// </summary>
        internal static string programTitle {
            get {
                return ResourceManager.GetString("programTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string saveButton {
            get {
                return ResourceManager.GetString("saveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settingsTabTitle {
            get {
                return ResourceManager.GetString("settingsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Audio Bitrate determines the quality of the audio output.
        ///The higher the bitrate the better the quality.
        ///
        ///Recommended: Minimum 32 Kbps.
        /// </summary>
        internal static string tooltipAudioBr {
            get {
                return ResourceManager.GetString("tooltipAudioBr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both audio codecs provide high quality at low bitrates.
        ///
        ///Recommended: Nero AAC.
        /// </summary>
        internal static string tooltipAudioCodec {
            get {
                return ResourceManager.GetString("tooltipAudioCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matroska: 
        ///The Matroska Multimedia Container is an open standard free container format, a file 
        ///format that can hold an unlimited number of video, audio, picture or subtitle tracks
        /// inside a single file.
        ///
        ///MP4:
        ///It is a multimedia container format standard specified as a part of MPEG-4. It is most 
        ///commonly used to store digital audio and digital video streams, especially those defined
        /// by MPEG..
        /// </summary>
        internal static string tooltipContainer {
            get {
                return ResourceManager.GetString("tooltipContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video denoising is the process of removing noise 
        ///from a video signal..
        /// </summary>
        internal static string tooltipDenoise {
            get {
                return ResourceManager.GetString("tooltipDenoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldDeinterlace: 
        ///This filter provides functionality similar to the postprocessing function 
        ///of Telecide. You can use it for pure interlaced streams.
        /// </summary>
        internal static string tooltipField {
            get {
                return ResourceManager.GetString("tooltipField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target File Size means that the program will try to get the
        ///output filesize as close as it can to the determined size.
        ///
        ///Things that could make the output bigger than set:
        ///- Attachments (Some fonts take over 5mb)
        ///- VFR (Variable FrameRate)
        ///
        ///Recommended
        ///- Minimum 50 mb for 20 min anime
        ///- Minimum 120 mb for TV-Show
        ///- Minmum 300mb for a Movie.
        /// </summary>
        internal static string tooltipFileSize {
            get {
                return ResourceManager.GetString("tooltipFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality determines the video quality of the outputted file.
        ///
        ///Settings:
        ///- Medium (Fast encoding time)
        ///- High (Normal encoding time)
        ///- Verry High (Long encoding time)
        ///- PSP (Fast, can be played on PSP)
        ///- IPOD (Fast, can be played on Ipod)
        ///- PS3/XBOX (Fast, can be played on Ipod).
        /// </summary>
        internal static string tooltipQuality {
            get {
                return ResourceManager.GetString("tooltipQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With a resizing filter you can easily resize a video to a 
        ///preferred aspect ratio. Using these filters you can either
        ///soften the image or sharpen it.
        ///
        ///Recommended: 
        ///- Soft for low bitrates
        ///- Sharp for high bitrates.
        /// </summary>
        internal static string tooltipResize {
            get {
                return ResourceManager.GetString("tooltipResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Subtitle file to use.
        /// </summary>
        internal static string tooltipSub {
            get {
                return ResourceManager.GetString("tooltipSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average (Variable) Bit Rate is used to determine the best quality at the lowest possible quantizizer 
        ///while maintaining the average bit rate. The higher the bitrate, the better the output quality. 
        ///
        ///In this mode the target video filesize can be predicted. 
        ///A basic calculation is 50 bitrate equals 10mb every 20 mins.
        ///
        ///Recommended: 
        ///- Minimum 250 for anime
        ///- Minimum 300 for TV-Shows/movies.
        /// </summary>
        internal static string tooltipVideoBr {
            get {
                return ResourceManager.GetString("tooltipVideoBr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X264: It is a free software library for encoding video streams 
        ///into the H.264/MPEG-4 AVC format.
        ///
        ///Xvid (formerly &quot;XviD&quot;) is a video codec library following the MPEG-4 standard,
        /// specifically MPEG-4 Part 2 Advanced Simple Profile (ASP). It uses ASP 
        ///features..
        /// </summary>
        internal static string tooltipVideoCodec {
            get {
                return ResourceManager.GetString("tooltipVideoCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width and heigth of the re-encoded video..
        /// </summary>
        internal static string tooltipWidthHeight {
            get {
                return ResourceManager.GetString("tooltipWidthHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit Rate:.
        /// </summary>
        internal static string videoBitRate {
            get {
                return ResourceManager.GetString("videoBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codec:.
        /// </summary>
        internal static string videoCodec {
            get {
                return ResourceManager.GetString("videoCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size:.
        /// </summary>
        internal static string videoFileSize {
            get {
                return ResourceManager.GetString("videoFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Options.
        /// </summary>
        internal static string videoOptionsTitle {
            get {
                return ResourceManager.GetString("videoOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        internal static string videoQuality {
            get {
                return ResourceManager.GetString("videoQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium;High;Very High;Very High (+50mb anime);Very High (-50mb anime);Very High (TV-Shows/Movies);CRF (Anime);Ipod;PSP;PS3/XBOX.
        /// </summary>
        internal static string videoQualityOptions {
            get {
                return ResourceManager.GetString("videoQualityOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When done.
        /// </summary>
        internal static string whenDone {
            get {
                return ResourceManager.GetString("whenDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Nothing;Hibernate;Standby;Shutdown.
        /// </summary>
        internal static string whenDoneOptions {
            get {
                return ResourceManager.GetString("whenDoneOptions", resourceCulture);
            }
        }
    }
}
