//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniTech.MiniCoder.Core.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Turkish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Turkish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniCoder.Core.Languages.Turkish", typeof(Turkish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulamalar.
        /// </summary>
        internal static string applicationsButton {
            get {
                return ResourceManager.GetString("applicationsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit Oranı:.
        /// </summary>
        internal static string audioBitrate {
            get {
                return ResourceManager.GetString("audioBitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodek:.
        /// </summary>
        internal static string audioCodec {
            get {
                return ResourceManager.GetString("audioCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ses Dekode ediliyor.
        /// </summary>
        internal static string audioDecodingMessage {
            get {
                return ResourceManager.GetString("audioDecodingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ses Enkode ediliyor:.
        /// </summary>
        internal static string audioEncodingMessage {
            get {
                return ResourceManager.GetString("audioEncodingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ses Parçası Enkode ediliyor.
        /// </summary>
        internal static string audioEncodingTrack {
            get {
                return ResourceManager.GetString("audioEncodingTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ses Ayarları.
        /// </summary>
        internal static string audioOptionsTitle {
            get {
                return ResourceManager.GetString("audioOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ses.
        /// </summary>
        internal static string audioTabTitle {
            get {
                return ResourceManager.GetString("audioTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        internal static string containerFormat {
            get {
                return ResourceManager.GetString("containerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konteyner.
        /// </summary>
        internal static string containerOptionsTitle {
            get {
                return ResourceManager.GetString("containerOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çekirdek.
        /// </summary>
        internal static string coreTabTitle {
            get {
                return ResourceManager.GetString("coreTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özel.
        /// </summary>
        internal static string customButton {
            get {
                return ResourceManager.GetString("customButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        internal static string customFilterCancel {
            get {
                return ResourceManager.GetString("customFilterCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğer varsayılan filtreyi iptal etmek istiyorsanız Ayarlar sayfasından iptal edin..
        /// </summary>
        internal static string customFilterNote {
            get {
                return ResourceManager.GetString("customFilterNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        internal static string customFilterOK {
            get {
                return ResourceManager.GetString("customFilterOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kendi Özel Avisynth Filtrelerinizi Girin.
        /// </summary>
        internal static string customFilterText {
            get {
                return ResourceManager.GetString("customFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özel Filtreler.
        /// </summary>
        internal static string customFilterTitle {
            get {
                return ResourceManager.GetString("customFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özel Yollar.
        /// </summary>
        internal static string customPathsTitle {
            get {
                return ResourceManager.GetString("customPathsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demux İptal edildi.
        /// </summary>
        internal static string demuxingAbortedMessage {
            get {
                return ResourceManager.GetString("demuxingAbortedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demux Tamamlandı.
        /// </summary>
        internal static string demuxingCompleteMessage {
            get {
                return ResourceManager.GetString("demuxingCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demux Ediliyor.
        /// </summary>
        internal static string demuxingMessage {
            get {
                return ResourceManager.GetString("demuxingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MKV Parçaları Demux Ediliyor.
        /// </summary>
        internal static string demuxingMkv {
            get {
                return ResourceManager.GetString("demuxingMkv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekler Demux Ediliyor.
        /// </summary>
        internal static string demuxingMkvAttachments {
            get {
                return ResourceManager.GetString("demuxingMkvAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölümler Demux Ediliyor.
        /// </summary>
        internal static string demuxingMkvChapters {
            get {
                return ResourceManager.GetString("demuxingMkvChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP4 Ses Parçası Demux Ediliyor.
        /// </summary>
        internal static string demuxingmp4Audio {
            get {
                return ResourceManager.GetString("demuxingmp4Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP4 Görüntü Parçası Demux Ediliyor.
        /// </summary>
        internal static string demuxingmp4Video {
            get {
                return ResourceManager.GetString("demuxingmp4Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOB dosyalarının dizinlenmesine başlandı.
        /// </summary>
        internal static string demuxingVob {
            get {
                return ResourceManager.GetString("demuxingVob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölümlerin getirilmesine başlandı..
        /// </summary>
        internal static string demuxingvobChapters {
            get {
                return ResourceManager.GetString("demuxingvobChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altyazıların getirilmesine başlandı..
        /// </summary>
        internal static string demuxingvobSubs {
            get {
                return ResourceManager.GetString("demuxingvobSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başla.
        /// </summary>
        internal static string encodeStartButton {
            get {
                return ResourceManager.GetString("encodeStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dur.
        /// </summary>
        internal static string encodeStopButton {
            get {
                return ResourceManager.GetString("encodeStopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enkode etme Tamamlandı.
        /// </summary>
        internal static string encodingComplete {
            get {
                return ResourceManager.GetString("encodingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekleri Yoksay.
        /// </summary>
        internal static string encodingIgnoreAttachments {
            get {
                return ResourceManager.GetString("encodingIgnoreAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesi Yoksay.
        /// </summary>
        internal static string encodingIgnoreAudio {
            get {
                return ResourceManager.GetString("encodingIgnoreAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölümleri Yoksay.
        /// </summary>
        internal static string encodingIgnoreChapters {
            get {
                return ResourceManager.GetString("encodingIgnoreChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altyazıları Yoksay.
        /// </summary>
        internal static string encodingIgnoreSubs {
            get {
                return ResourceManager.GetString("encodingIgnoreSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatadan sonra bir sonraki dosyaya devam et.
        /// </summary>
        internal static string encodingNextError {
            get {
                return ResourceManager.GetString("encodingNextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görüntü önizlemesi göster (Sadece Hata Ayıklama).
        /// </summary>
        internal static string encodingShowVideoPreview {
            get {
                return ResourceManager.GetString("encodingShowVideoPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enkode Etme.
        /// </summary>
        internal static string encodingTitle {
            get {
                return ResourceManager.GetString("encodingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görüntü Enkode Etme.
        /// </summary>
        internal static string encodingVideoPass {
            get {
                return ResourceManager.GetString("encodingVideoPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theora vidyo Enkode Etme.
        /// </summary>
        internal static string encodingVideoTheora {
            get {
                return ResourceManager.GetString("encodingVideoTheora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir hata oluştu sanki! Hata raporu göndermek istiyor musunuz?.
        /// </summary>
        internal static string errorWarningMessage {
            get {
                return ResourceManager.GetString("errorWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata!.
        /// </summary>
        internal static string errorWarningTitle {
            get {
                return ResourceManager.GetString("errorWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Bilgisi Getiriliyor.
        /// </summary>
        internal static string fileInfoFetch {
            get {
                return ResourceManager.GetString("fileInfoFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtre Ayarları.
        /// </summary>
        internal static string filterOptionsTitle {
            get {
                return ResourceManager.GetString("filterOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVC dizinleniyor.
        /// </summary>
        internal static string indexingAvc {
            get {
                return ResourceManager.GetString("indexingAvc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dizinleme İptal Edildi.
        /// </summary>
        internal static string indexingAvcAbort {
            get {
                return ResourceManager.GetString("indexingAvcAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVC Dizinleme Tamamlandı.
        /// </summary>
        internal static string indexingAvcCompleted {
            get {
                return ResourceManager.GetString("indexingAvcCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUI Hazır.
        /// </summary>
        internal static string infoLabel {
            get {
                return ResourceManager.GetString("infoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş (Dosya VFR ise işaretleyin).
        /// </summary>
        internal static string inputColumn1Title {
            get {
                return ResourceManager.GetString("inputColumn1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal Edildi.
        /// </summary>
        internal static string inputColumn2StatusAborted {
            get {
                return ResourceManager.GetString("inputColumn2StatusAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamamlandı.
        /// </summary>
        internal static string inputColumn2StatusDone {
            get {
                return ResourceManager.GetString("inputColumn2StatusDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enkode edilyor.
        /// </summary>
        internal static string inputColumn2StatusEncoding {
            get {
                return ResourceManager.GetString("inputColumn2StatusEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        internal static string inputColumn2StatusError {
            get {
                return ResourceManager.GetString("inputColumn2StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazır.
        /// </summary>
        internal static string inputColumn2StatusReady {
            get {
                return ResourceManager.GetString("inputColumn2StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string inputColumn2StatusTitle {
            get {
                return ResourceManager.GetString("inputColumn2StatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        internal static string inputTabTitle {
            get {
                return ResourceManager.GetString("inputTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopyala.
        /// </summary>
        internal static string logMenuCopy {
            get {
                return ResourceManager.GetString("logMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata raporu gönder.
        /// </summary>
        internal static string logMenuSend {
            get {
                return ResourceManager.GetString("logMenuSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Günlük.
        /// </summary>
        internal static string logTabTitle {
            get {
                return ResourceManager.GetString("logTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        internal static string menuAdd {
            get {
                return ResourceManager.GetString("menuAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        internal static string menuClear {
            get {
                return ResourceManager.GetString("menuClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaldır.
        /// </summary>
        internal static string menuRemove {
            get {
                return ResourceManager.GetString("menuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muxing:.
        /// </summary>
        internal static string muxingMessage {
            get {
                return ResourceManager.GetString("muxingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muxing/Demuxing.
        /// </summary>
        internal static string muxingTabTitle {
            get {
                return ResourceManager.GetString("muxingTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haberler.
        /// </summary>
        internal static string newsTabTitle {
            get {
                return ResourceManager.GetString("newsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string optionsTabTitle {
            get {
                return ResourceManager.GetString("optionsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer.
        /// </summary>
        internal static string otherTabTitle {
            get {
                return ResourceManager.GetString("otherTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıktı Dizini:.
        /// </summary>
        internal static string outputDirectory {
            get {
                return ResourceManager.GetString("outputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vidyo başlık ilanını kapat.
        /// </summary>
        internal static string outputDisableVideoAdvert {
            get {
                return ResourceManager.GetString("outputDisableVideoAdvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıktı Ayarları.
        /// </summary>
        internal static string outputSettingsTitle {
            get {
                return ResourceManager.GetString("outputSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eklentiler.
        /// </summary>
        internal static string pluginsTabTitle {
            get {
                return ResourceManager.GetString("pluginsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denoiser:.
        /// </summary>
        internal static string postDenoiser {
            get {
                return ResourceManager.GetString("postDenoiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yok;Hafif;Orta;Ağır;Çılgın.
        /// </summary>
        internal static string postDenoiserOptions {
            get {
                return ResourceManager.GetString("postDenoiserOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Processing.
        /// </summary>
        internal static string postprocessingOptionsTitle {
            get {
                return ResourceManager.GetString("postprocessingOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keskinlik:.
        /// </summary>
        internal static string postSharpen {
            get {
                return ResourceManager.GetString("postSharpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yok;Hafif;Orta;Ağır;Çılgın.
        /// </summary>
        internal static string postSharpenOptions {
            get {
                return ResourceManager.GetString("postSharpenOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altyazı:.
        /// </summary>
        internal static string postSubtitle {
            get {
                return ResourceManager.GetString("postSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field:.
        /// </summary>
        internal static string preField {
            get {
                return ResourceManager.GetString("preField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Processing.
        /// </summary>
        internal static string preprocessingOptionsTitle {
            get {
                return ResourceManager.GetString("preprocessingOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boyutlandır:.
        /// </summary>
        internal static string preResize {
            get {
                return ResourceManager.GetString("preResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yok;Yumuşak;Bağımsız;Keskin;Çok Keskin (Lanczos64);Çok Keskin (Spline36).
        /// </summary>
        internal static string preResizeOptions {
            get {
                return ResourceManager.GetString("preResizeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En/Boy:.
        /// </summary>
        internal static string preWidthHeight {
            get {
                return ResourceManager.GetString("preWidthHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öncelik:.
        /// </summary>
        internal static string processPriority {
            get {
                return ResourceManager.GetString("processPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düşük;Normalin Altında;Normal;Normalin Üstünde;Yüksek;Eş-zamanlı.
        /// </summary>
        internal static string processPriorityOptions {
            get {
                return ResourceManager.GetString("processPriorityOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşleme Ayarları.
        /// </summary>
        internal static string processSettingsTitle {
            get {
                return ResourceManager.GetString("processSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiniCoder Enkoding GUI.
        /// </summary>
        internal static string programTitle {
            get {
                return ResourceManager.GetString("programTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        internal static string saveButton {
            get {
                return ResourceManager.GetString("saveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string settingsTabTitle {
            get {
                return ResourceManager.GetString("settingsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değişken Ses Bitoranı ses çıkışının kalitesini belirler.\r\nDaha yüksek bitoranı daha yüksek kalite..
        /// </summary>
        internal static string tooltipAudioBr {
            get {
                return ResourceManager.GetString("tooltipAudioBr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Araç ipucu yok.
        /// </summary>
        internal static string tooltipContainer {
            get {
                return ResourceManager.GetString("tooltipContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vidyo denoising vidyo sinyalinden gürültüyü \r\nkaldırma işlemidir.
        /// </summary>
        internal static string tooltipDenoise {
            get {
                return ResourceManager.GetString("tooltipDenoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Araç ipucu yok.
        /// </summary>
        internal static string tooltipField {
            get {
                return ResourceManager.GetString("tooltipField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hedef Dosya Boyutu programın çıktı dosyasının boyutunu belirtilen değere \r\n en yakın yapabileceği değere ayarlamasını sağlar.
        /// </summary>
        internal static string tooltipFileSize {
            get {
                return ResourceManager.GetString("tooltipFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalite çıktı dosyasının vidyo kalitesini belirler..
        /// </summary>
        internal static string tooltipQuality {
            get {
                return ResourceManager.GetString("tooltipQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeniden boyutlandırma filtresiyle vidyoyou kolayca yeniden boyutlandırabilirsiniz \r\n tercih ettiğiniz en-boy oranına. Bu filtreleri kullanarak\r\ngörüntüyü yumuşatabilir veya keskinleştirebilirsiniz..
        /// </summary>
        internal static string tooltipResize {
            get {
                return ResourceManager.GetString("tooltipResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanılacak altyazı dosyasını seçin.
        /// </summary>
        internal static string tooltipSub {
            get {
                return ResourceManager.GetString("tooltipSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Averaj (Değişken) Bit Oranı mümkün olan en düşük quantizizerde en iyi kaliteyi belirtmeye yarar \r\n averaj bit oranını sürdürürken. Daha yüksek bitoranı daha yüksek kalite..
        /// </summary>
        internal static string tooltipVideoBr {
            get {
                return ResourceManager.GetString("tooltipVideoBr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Araç ipucu yok.
        /// </summary>
        internal static string tooltipVideoCodec {
            get {
                return ResourceManager.GetString("tooltipVideoCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekrar enkode edilmiş vidyonun eni ve boyu..
        /// </summary>
        internal static string tooltipWidthHeight {
            get {
                return ResourceManager.GetString("tooltipWidthHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        internal static string updateCancelButton {
            get {
                return ResourceManager.GetString("updateCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        internal static string updateColumn1 {
            get {
                return ResourceManager.GetString("updateColumn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        internal static string updateColumn2 {
            get {
                return ResourceManager.GetString("updateColumn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut Versiyon.
        /// </summary>
        internal static string updateColumn3 {
            get {
                return ResourceManager.GetString("updateColumn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Versiyon.
        /// </summary>
        internal static string updateColumn4 {
            get {
                return ResourceManager.GetString("updateColumn4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string updateColumn5 {
            get {
                return ResourceManager.GetString("updateColumn5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özel Yollar.
        /// </summary>
        internal static string updateCustomPath {
            get {
                return ResourceManager.GetString("updateCustomPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelleme mevcut. Şimdi indirmek ister misiniz?.
        /// </summary>
        internal static string updateMessage {
            get {
                return ResourceManager.GetString("updateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiniCoder Güncelleyici.
        /// </summary>
        internal static string updaterTitle {
            get {
                return ResourceManager.GetString("updaterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        internal static string updateUpdateButton {
            get {
                return ResourceManager.GetString("updateUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VFR Ayıklama.
        /// </summary>
        internal static string vfrParsing {
            get {
                return ResourceManager.GetString("vfrParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VFR Ayıklama iptal edildi.
        /// </summary>
        internal static string vfrParsingAborted {
            get {
                return ResourceManager.GetString("vfrParsingAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VFR Ayıklama tamamlandı.
        /// </summary>
        internal static string vfrParsingCompleted {
            get {
                return ResourceManager.GetString("vfrParsingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit Oranı:.
        /// </summary>
        internal static string videoBitRate {
            get {
                return ResourceManager.GetString("videoBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodek:.
        /// </summary>
        internal static string videoCodec {
            get {
                return ResourceManager.GetString("videoCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Boy.:.
        /// </summary>
        internal static string videoFileSize {
            get {
                return ResourceManager.GetString("videoFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vidyo Ayarları.
        /// </summary>
        internal static string videoOptionsTitle {
            get {
                return ResourceManager.GetString("videoOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalte:.
        /// </summary>
        internal static string videoQuality {
            get {
                return ResourceManager.GetString("videoQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orta;Yüksek;Çok Yüksek;Çok Yüksek (+50mb anime);Çok Yüksek (-50mb anime);Çok Yüksek (TV-Şovları/Filmler);CRF (Anime);Ipod;PSP;PS3/XBOX.
        /// </summary>
        internal static string videoQualityOptions {
            get {
                return ResourceManager.GetString("videoQualityOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vidyo.
        /// </summary>
        internal static string videoTabTitle {
            get {
                return ResourceManager.GetString("videoTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bittiğinde.
        /// </summary>
        internal static string whenDone {
            get {
                return ResourceManager.GetString("whenDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bişiy Yapma;Hazırda Beklet;Bekleme Konumu;Bilgisayarı Kapat.
        /// </summary>
        internal static string whenDoneOptions {
            get {
                return ResourceManager.GetString("whenDoneOptions", resourceCulture);
            }
        }
    }
}
